# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd53b26632e04908d6e3dbd346f59921aa3fb4d7e35ba86877e297a93b4dff210a02d6bd5522f9fb46237496e56105c47f6a6458076e290a88d36c323902ad4

test:
  secret_key_base: bbf6455414ae7d2186561a51dfd9fdd2d651fd21cd2c1629a073d6c3fa0b7ddf81c57b07ab5feab39177d2d5b9170db9dbcbada7e6748b35a183df06d9fa9143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
